site_name: Nihon Automação
site_url: https://example.com

# Navegação
nav:
  - Início: index.md
  - Visão de Produto e Projeto:
      - Cenário Atual do Cliente e do Negócio: produto.md
      - Solução Proposta: solucao.md
      - Estratégias de Engenharia de Software: estrategias.md
      - Cronograma e Entregas: cronograma.md
      - Interação entre equipe e cliente: interacao.md
      - Lições Aprendidas: licoes.md

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/house
  features:
    - navigation.footer
    - navigation.instant  
    - navigation.tabs      
    - content.code.copy     
    - content.tabs.link   
    - content.tooltips      
    - content.tables       
  palette:
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Modo Claro
      primary: blue
      accent: deep purple
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Modo Escuro
      primary: blue
      accent: deep purple

markdown_extensions:
  - attr_list
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Extra CSS para ajustar tabelas
extra_css:
  - css/custom.css
